version: "3"

services:
  server:
    build: .
    volumes:
      - ./server/:/home/
    ports:
      - "25565:25565"
    stdin_open: true
    tty: true

    # Java command options
    # - -Xmx specifies maximum heap memory size
    # - -Xms specifies heap memory usage at start
    # - -XX:+UseZGC enables Z garbage collector, which may improve performance
    # Minecraft options
    # - --bonusChest creates bonus chests during world creation
    # - --eraseCache clears cache before running server
    command: >
      sh -c "
        java -Xmx1024M -Xms1024M -jar /opt/server.jar
      "
